"""Add process instance key in group table.

Revision ID: 105639668925
Revises: 8a50635278f7
Create Date: 2023-10-12 15:01:17.985200

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "105639668925"
down_revision: str | None = "8a50635278f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("group_process_instance_key", sa.BigInteger(), nullable=True))
    op.create_unique_constraint(op.f("uq_group_group_process_instance_key"), "group", ["group_process_instance_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_group_group_process_instance_key"), "group", type_="unique")
    op.drop_column("group", "group_process_instance_key")
    # ### end Alembic commands ###
