"""Add keeping tmo_id in group

Revision ID: 2f7cd84f25ff
Revises: 105639668925
Create Date: 2023-10-16 14:25:49.812800

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f7cd84f25ff"
down_revision: str | None = "105639668925"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("tmo_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group", "tmo_id")
    # ### end Alembic commands ###
