"""Add aggregate column for group table

Revision ID: 532a7010a9d4
Revises: 98cdcdd64c49
Create Date: 2023-11-28 15:57:01.155890

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532a7010a9d4'
down_revision: str | None = '98cdcdd64c49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_aggregate', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_aggregate')
    # ### end Alembic commands ###
