"""Add ranges object to group template.

Revision ID: 5b48c0470bdb
Revises: ddcd9c681f59
Create Date: 2024-07-12 11:44:01.434935

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b48c0470bdb'
down_revision: str | None = 'ddcd9c681f59'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_template', sa.Column('column_filters', sa.JSON(), nullable=False))
    op.add_column('group_template', sa.Column('ranges_object', sa.JSON(), nullable=False))
    op.drop_column('group_template', 'columnFilters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_template', sa.Column('columnFilters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('group_template', 'ranges_object')
    op.drop_column('group_template', 'column_filters')
    # ### end Alembic commands ###
