"""Init

Revision ID: 8a50635278f7
Revises: 
Create Date: 2023-10-12 14:09:18.305200

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a50635278f7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    group_type = op.create_table(
        "group_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_type")),
        sa.UniqueConstraint("name", name=op.f("uq_group_type_name")),
    )
    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_name", sa.String(), nullable=False),
        sa.Column("group_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_type_id"], ["group_type.id"], name=op.f("fk_group_group_type_id_group_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group")),
        sa.UniqueConstraint("group_name", name=op.f("uq_group_group_name")),
    )
    op.create_table(
        "element",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], name=op.f("fk_element_group_id_group"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_element")),
        sa.UniqueConstraint("entity_id", "group_id", name=op.f("uq_element_entity_id_group_id")),
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        group_type,
        [{"id": 1, "name": "object_group"}, {"id": 2, "name": "process_group"}],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("element")
    op.drop_table("group")
    op.drop_table("group_type")
    # ### end Alembic commands ###
