"""Add group filter column

Revision ID: 98cdcdd64c49
Revises: dba887d19689
Create Date: 2023-11-09 22:12:22.000218

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "98cdcdd64c49"
down_revision: str | None = "dba887d19689"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("column_filters", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group", "column_filters")
    # ### end Alembic commands ###
