"""Add range objects to group

Revision ID: bee0a2f49059
Revises: bccb96dff802
Create Date: 2024-07-12 14:13:47.281187

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee0a2f49059'
down_revision: str | None = 'bccb96dff802'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('ranges_object', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'ranges_object')
    # ### end Alembic commands ###
