"""Add minimal quantity for auto generate group

Revision ID: d23e1525575a
Revises: 532a7010a9d4
Create Date: 2024-03-25 10:42:20.145149

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23e1525575a'
down_revision: str | None = '532a7010a9d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('min_qnt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'min_qnt')
    # ### end Alembic commands ###
