"""Add is_valid for model

Revision ID: dba887d19689
Revises: 2f7cd84f25ff
Create Date: 2023-10-23 16:04:48.494680

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dba887d19689"
down_revision: str | None = "2f7cd84f25ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("is_valid", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group", "is_valid")
    # ### end Alembic commands ###
