"""Add template for group

Revision ID: ddcd9c681f59
Revises: d23e1525575a
Create Date: 2024-07-05 12:54:19.529269

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcd9c681f59'
down_revision: str | None = 'd23e1525575a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('columnFilters', sa.JSON(), nullable=False),
    sa.Column('identical', sa.JSON(), nullable=False),
    sa.Column('min_qnt', sa.Integer(), nullable=False),
    sa.Column('tmo_id', sa.Integer(), nullable=False),
    sa.Column('group_type_id_for_template', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_type_id_for_template'], ['group_type.id'], name=op.f('fk_group_template_group_type_id_for_template_group_type'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_template')),
    sa.UniqueConstraint('name', name=op.f('uq_group_template_name'))
    )
    op.add_column('group', sa.Column('group_template_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_group_group_type_id_group_type', 'group', type_='foreignkey')
    op.create_foreign_key(op.f('fk_group_group_template_id_group_template'), 'group', 'group_template', ['group_template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_group_group_type_id_group_type'), 'group', 'group_type', ['group_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_group_group_type_id_group_type'), 'group', type_='foreignkey')
    op.drop_constraint(op.f('fk_group_group_template_id_group_template'), 'group', type_='foreignkey')
    op.create_foreign_key('fk_group_group_type_id_group_type', 'group', 'group_type', ['group_type_id'], ['id'])
    op.drop_column('group', 'group_template_id')
    op.drop_table('group_template')
    # ### end Alembic commands ###
